image:
  file: Dockerfile
tasks:
  - init: >
      pip install pylint cardboardlint && 
      pip3 install -r requirements.txt
    command: >
      cardboardlinter --refspec master &&
      python3 DeepSpeech.py
